package com.gamitour.modelo;
// Generated Apr 27, 2018 8:12:19 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Actividad generated by hbm2java
 */
@Entity
@Table(name = "actividad", catalog = "gamitour", uniqueConstraints = @UniqueConstraint(columnNames = "nombre"))
public class Actividad implements java.io.Serializable {

	private Integer idactividad;
	private String nombre;
	private Date fechainicio;
	private Date fechafin;
	private int numparticipantes;
	private double precio;
	private int puntos;
	private String latitud;
	private String longitud;
	private Set<ClienteHasActividad> clienteHasActividads = new HashSet<ClienteHasActividad>(0);
	private Set<Imagenactividad> imagenactividads = new HashSet<Imagenactividad>(0);

	public Actividad() {
	}

	public Actividad(String nombre, Date fechainicio, int numparticipantes, double precio, int puntos, String latitud,
			String longitud) {
		this.nombre = nombre;
		this.fechainicio = fechainicio;
		this.numparticipantes = numparticipantes;
		this.precio = precio;
		this.puntos = puntos;
		this.latitud = latitud;
		this.longitud = longitud;
	}

	public Actividad(String nombre, Date fechainicio, Date fechafin, int numparticipantes, double precio, int puntos,
			String latitud, String longitud, Set<ClienteHasActividad> clienteHasActividads,
			Set<Imagenactividad> imagenactividads) {
		this.nombre = nombre;
		this.fechainicio = fechainicio;
		this.fechafin = fechafin;
		this.numparticipantes = numparticipantes;
		this.precio = precio;
		this.puntos = puntos;
		this.latitud = latitud;
		this.longitud = longitud;
		this.clienteHasActividads = clienteHasActividads;
		this.imagenactividads = imagenactividads;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idactividad", unique = true, nullable = false)
	public Integer getIdactividad() {
		return this.idactividad;
	}

	public void setIdactividad(Integer idactividad) {
		this.idactividad = idactividad;
	}

	@Column(name = "nombre", unique = true, nullable = false, length = 60)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechainicio", nullable = false, length = 10)
	public Date getFechainicio() {
		return this.fechainicio;
	}

	public void setFechainicio(Date fechainicio) {
		this.fechainicio = fechainicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechafin", length = 10)
	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

	@Column(name = "numparticipantes", nullable = false)
	public int getNumparticipantes() {
		return this.numparticipantes;
	}

	public void setNumparticipantes(int numparticipantes) {
		this.numparticipantes = numparticipantes;
	}

	@Column(name = "precio", nullable = false, precision = 22, scale = 0)
	public double getPrecio() {
		return this.precio;
	}

	public void setPrecio(double precio) {
		this.precio = precio;
	}

	@Column(name = "puntos", nullable = false)
	public int getPuntos() {
		return this.puntos;
	}

	public void setPuntos(int puntos) {
		this.puntos = puntos;
	}

	@Column(name = "latitud", nullable = false, length = 45)
	public String getLatitud() {
		return this.latitud;
	}

	public void setLatitud(String latitud) {
		this.latitud = latitud;
	}

	@Column(name = "longitud", nullable = false, length = 45)
	public String getLongitud() {
		return this.longitud;
	}

	public void setLongitud(String longitud) {
		this.longitud = longitud;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "actividad")
	public Set<ClienteHasActividad> getClienteHasActividads() {
		return this.clienteHasActividads;
	}

	public void setClienteHasActividads(Set<ClienteHasActividad> clienteHasActividads) {
		this.clienteHasActividads = clienteHasActividads;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "actividad")
	public Set<Imagenactividad> getImagenactividads() {
		return this.imagenactividads;
	}

	public void setImagenactividads(Set<Imagenactividad> imagenactividads) {
		this.imagenactividads = imagenactividads;
	}

}
