package com.gamitour.modelo;
// Generated Apr 27, 2018 8:12:19 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClienteHasActividad generated by hbm2java
 */
@Entity
@Table(name = "cliente_has_actividad", catalog = "gamitour")
public class ClienteHasActividad implements java.io.Serializable {

	private Integer idClienteHasActividad;
	private Actividad actividad;
	private Cliente cliente;
	private Date fechaReserva;
	private int numPersonas;

	public ClienteHasActividad() {
	}

	public ClienteHasActividad(Actividad actividad, Cliente cliente, Date fechaReserva, int numPersonas) {
		this.actividad = actividad;
		this.cliente = cliente;
		this.fechaReserva = fechaReserva;
		this.numPersonas = numPersonas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCliente_has_actividad", unique = true, nullable = false)
	public Integer getIdClienteHasActividad() {
		return this.idClienteHasActividad;
	}

	public void setIdClienteHasActividad(Integer idClienteHasActividad) {
		this.idClienteHasActividad = idClienteHasActividad;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "actividad_idactividad", nullable = false)
	public Actividad getActividad() {
		return this.actividad;
	}

	public void setActividad(Actividad actividad) {
		this.actividad = actividad;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cliente_idcliente", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaReserva", nullable = false, length = 10)
	public Date getFechaReserva() {
		return this.fechaReserva;
	}

	public void setFechaReserva(Date fechaReserva) {
		this.fechaReserva = fechaReserva;
	}

	@Column(name = "numPersonas", nullable = false)
	public int getNumPersonas() {
		return this.numPersonas;
	}

	public void setNumPersonas(int numPersonas) {
		this.numPersonas = numPersonas;
	}

}
