package com.gamitour.modelo;
// Generated Apr 27, 2018 8:12:19 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Imagenactividad generated by hbm2java
 */
@Entity
@Table(name = "imagenactividad", catalog = "gamitour", uniqueConstraints = @UniqueConstraint(columnNames = "idActividad"))
public class Imagenactividad implements java.io.Serializable {

	private Integer idImagenActividad;
	private Actividad actividad;
	private String titulo;
	private String archivo;

	public Imagenactividad() {
	}

	public Imagenactividad(Actividad actividad, String archivo) {
		this.actividad = actividad;
		this.archivo = archivo;
	}

	public Imagenactividad(Actividad actividad, String titulo, String archivo) {
		this.actividad = actividad;
		this.titulo = titulo;
		this.archivo = archivo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idImagenActividad", unique = true, nullable = false)
	public Integer getIdImagenActividad() {
		return this.idImagenActividad;
	}

	public void setIdImagenActividad(Integer idImagenActividad) {
		this.idImagenActividad = idImagenActividad;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idActividad", unique = true, nullable = false)
	public Actividad getActividad() {
		return this.actividad;
	}

	public void setActividad(Actividad actividad) {
		this.actividad = actividad;
	}

	@Column(name = "titulo", length = 45)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "archivo", nullable = false, length = 45)
	public String getArchivo() {
		return this.archivo;
	}

	public void setArchivo(String archivo) {
		this.archivo = archivo;
	}

}
