package com.gamitour.modelo;
// Generated Apr 27, 2018 8:12:19 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Parada generated by hbm2java
 */
@Entity
@Table(name = "parada", catalog = "gamitour", uniqueConstraints = @UniqueConstraint(columnNames = "nombre"))
public class Parada implements java.io.Serializable {

	private int idparada;
	private Itinerario itinerario;
	private String nombre;
	private int numeroParada;
	private String historia;
	private String anecdotario;
	private String gastronomia;
	private String imagen;
	private String video;
	private String latitud;
	private String longitud;
	private Set<Pruebacultural> pruebaculturals = new HashSet<Pruebacultural>(0);
	private Set<Pruebadeportiva> pruebadeportivas = new HashSet<Pruebadeportiva>(0);

	public Parada() {
	}

	public Parada(int idparada, Itinerario itinerario, String nombre, int numeroParada, String latitud,
			String longitud) {
		this.idparada = idparada;
		this.itinerario = itinerario;
		this.nombre = nombre;
		this.numeroParada = numeroParada;
		this.latitud = latitud;
		this.longitud = longitud;
	}

	public Parada(int idparada, Itinerario itinerario, String nombre, int numeroParada, String historia,
			String anecdotario, String gastronomia, String imagen, String video, String latitud, String longitud,
			Set<Pruebacultural> pruebaculturals, Set<Pruebadeportiva> pruebadeportivas) {
		this.idparada = idparada;
		this.itinerario = itinerario;
		this.nombre = nombre;
		this.numeroParada = numeroParada;
		this.historia = historia;
		this.anecdotario = anecdotario;
		this.gastronomia = gastronomia;
		this.imagen = imagen;
		this.video = video;
		this.latitud = latitud;
		this.longitud = longitud;
		this.pruebaculturals = pruebaculturals;
		this.pruebadeportivas = pruebadeportivas;
	}

	@Id

	@Column(name = "idparada", unique = true, nullable = false)
	public int getIdparada() {
		return this.idparada;
	}

	public void setIdparada(int idparada) {
		this.idparada = idparada;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "itinerario_iditinerario", nullable = false)
	public Itinerario getItinerario() {
		return this.itinerario;
	}

	public void setItinerario(Itinerario itinerario) {
		this.itinerario = itinerario;
	}

	@Column(name = "nombre", unique = true, nullable = false, length = 60)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "numeroParada", nullable = false)
	public int getNumeroParada() {
		return this.numeroParada;
	}

	public void setNumeroParada(int numeroParada) {
		this.numeroParada = numeroParada;
	}

	@Column(name = "historia", length = 200)
	public String getHistoria() {
		return this.historia;
	}

	public void setHistoria(String historia) {
		this.historia = historia;
	}

	@Column(name = "anecdotario", length = 200)
	public String getAnecdotario() {
		return this.anecdotario;
	}

	public void setAnecdotario(String anecdotario) {
		this.anecdotario = anecdotario;
	}

	@Column(name = "gastronomia", length = 200)
	public String getGastronomia() {
		return this.gastronomia;
	}

	public void setGastronomia(String gastronomia) {
		this.gastronomia = gastronomia;
	}

	@Column(name = "imagen", length = 45)
	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	@Column(name = "video", length = 45)
	public String getVideo() {
		return this.video;
	}

	public void setVideo(String video) {
		this.video = video;
	}

	@Column(name = "latitud", nullable = false, length = 45)
	public String getLatitud() {
		return this.latitud;
	}

	public void setLatitud(String latitud) {
		this.latitud = latitud;
	}

	@Column(name = "longitud", nullable = false, length = 45)
	public String getLongitud() {
		return this.longitud;
	}

	public void setLongitud(String longitud) {
		this.longitud = longitud;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "parada")
	public Set<Pruebacultural> getPruebaculturals() {
		return this.pruebaculturals;
	}

	public void setPruebaculturals(Set<Pruebacultural> pruebaculturals) {
		this.pruebaculturals = pruebaculturals;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "parada")
	public Set<Pruebadeportiva> getPruebadeportivas() {
		return this.pruebadeportivas;
	}

	public void setPruebadeportivas(Set<Pruebadeportiva> pruebadeportivas) {
		this.pruebadeportivas = pruebadeportivas;
	}

}
